/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---

            Last generated: Fri Mar 10 15:48:38 2000

            DO NOT EDIT!!!  (why ???) This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <QIcon>
#include "qtformtorg.h"
#include "prfconst.h"


extern QTFormtorg *Formtorg;

void QTFormtorg::initDialog () {
  this->resize(220, 230);
  this->setMinimumSize(220, 230);
  this->setMaximumSize(220, 230);

  for (int suit = 1; suit <= 4; suit++) {
    int y = 30*suit-20;
    for (int face = 6; face <= 10; face++) {
      int x = (face-6)*40+10;
      QString iName, oName;
      iName.sprintf(":/pics/bids/s%i%i.png", face, suit);
      oName.sprintf("g%i%i", face, suit);
      QPushButton *b = new QPushButton(this);
      b->setObjectName(oName);
      b->setGeometry(x, y, 40, 27);
      b->setMinimumSize(40, 27);
      b->setIconSize(QSize(40, 27));
      b->setIcon(QIcon(iName));
      // hack! hack!
      char slotName[128];
      sprintf(slotName, "1slotPushButtonClick%i%i()", face, suit);
      connect(b, SIGNAL(clicked()), this, slotName);
    }
  }

  bpass = new QPushButton(this);
  bpass->setGeometry(10,160,70,30);
  bpass->setMinimumSize(0,0);
  bpass->setObjectName("pass");
  bpass->setText("&Pass");

  bvist = new QPushButton(this);
  bvist->setGeometry(80,160,60,30);
  bvist->setMinimumSize(0,0);
  bvist->setObjectName("vist");
  bvist->setText("&Whist");

  b86 = new QPushButton(this);
  b86->setGeometry(140, 160, 70, 30);
  b86->setMinimumSize(0,0);
  b86->setObjectName("g86");
  b86->setText("&Misere");

  showbullet = new QPushButton(this);
  showbullet->setGeometry(110, 190, 100, 27);
  showbullet->setMinimumSize(0, 0);
  showbullet->setText("&Score");

  bgetback = new QPushButton(this);
  bgetback->setGeometry(10, 190, 100, 27);
  bgetback->setMinimumSize(0, 0);
  bgetback->setText("Get &back");

/*
  connect( b61, SIGNAL(clicked()),this, SLOT(slotPushButtonClick61( )) );
  connect( b62, SIGNAL(clicked()),this, SLOT(slotPushButtonClick62( )) );
  connect( b63, SIGNAL(clicked()),this, SLOT(slotPushButtonClick63( )) );
  connect( b64, SIGNAL(clicked()),this, SLOT(slotPushButtonClick64( )) );
  connect( b65, SIGNAL(clicked()),this, SLOT(slotPushButtonClick65( )) );

  connect( b71, SIGNAL(clicked()),this, SLOT(slotPushButtonClick71( )) );
  connect( b72, SIGNAL(clicked()),this, SLOT(slotPushButtonClick72( )) );
  connect( b73, SIGNAL(clicked()),this, SLOT(slotPushButtonClick73( )) );
  connect( b74, SIGNAL(clicked()),this, SLOT(slotPushButtonClick74( )) );
  connect( b75, SIGNAL(clicked()),this, SLOT(slotPushButtonClick75( )) );

  connect( b81, SIGNAL(clicked()),this, SLOT(slotPushButtonClick81( )) );
  connect( b82, SIGNAL(clicked()),this, SLOT(slotPushButtonClick82( )) );
  connect( b83, SIGNAL(clicked()),this, SLOT(slotPushButtonClick83( )) );
  connect( b84, SIGNAL(clicked()),this, SLOT(slotPushButtonClick84( )) );
  connect( b85, SIGNAL(clicked()),this, SLOT(slotPushButtonClick85( )) );

  connect( b91, SIGNAL(clicked()),this, SLOT(slotPushButtonClick91( )) );
  connect( b92, SIGNAL(clicked()),this, SLOT(slotPushButtonClick92( )) );
  connect( b93, SIGNAL(clicked()),this, SLOT(slotPushButtonClick93( )) );
  connect( b94, SIGNAL(clicked()),this, SLOT(slotPushButtonClick94( )) );
  connect( b95, SIGNAL(clicked()),this, SLOT(slotPushButtonClick95( )) );

  connect( b101, SIGNAL(clicked()),this, SLOT(slotPushButtonClick101( )) );
  connect( b102, SIGNAL(clicked()),this, SLOT(slotPushButtonClick102( )) );
  connect( b103, SIGNAL(clicked()),this, SLOT(slotPushButtonClick103( )) );
  connect( b104, SIGNAL(clicked()),this, SLOT(slotPushButtonClick104( )) );
  connect( b105, SIGNAL(clicked()),this, SLOT(slotPushButtonClick105()));
*/

  connect(b86, SIGNAL(clicked()), this, SLOT(slotPushButtonClick86()));
  connect(bpass, SIGNAL(clicked()), this, SLOT(slotPushButtonClickPass()));
  connect(bvist, SIGNAL(clicked()), this, SLOT(slotPushButtonClickVist()));
  connect(bgetback, SIGNAL(clicked()), this, SLOT(slotGetBackSnos()));
  connect(showbullet, SIGNAL(clicked()), this, SLOT(slotShowBullet()));
}
