/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---

            Last generated: Fri Mar 10 15:48:38 2000

            DO NOT EDIT!!!  (why ???) This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <QIcon>
#include "qtformtorg.h"
#include "prfconst.h"

/*
#include "pics/s101.xpm"
#include "pics/s102.xpm"
#include "pics/s103.xpm"
#include "pics/s104.xpm"
#include "pics/s105.xpm"
#include "pics/s61.xpm"
#include "pics/s62.xpm"
#include "pics/s63.xpm"
#include "pics/s64.xpm"
#include "pics/s65.xpm"
#include "pics/s71.xpm"
#include "pics/s72.xpm"
#include "pics/s73.xpm"
#include "pics/s74.xpm"
#include "pics/s75.xpm"
#include "pics/s81.xpm"
#include "pics/s82.xpm"
#include "pics/s83.xpm"
#include "pics/s84.xpm"
#include "pics/s85.xpm"
#include "pics/s91.xpm"
#include "pics/s92.xpm"
#include "pics/s93.xpm"
#include "pics/s94.xpm"
#include "pics/s95.xpm"
*/

extern QTFormtorg *Formtorg;

void QTFormtorg::initDialog () {
  this->resize(220,230);
  this->setMinimumSize(220,230);
  this->setMaximumSize(220,230);

  showbullet= new QPushButton("showbullet", this);
  showbullet->setGeometry(110,190,100,27);
  showbullet->setMinimumSize(0,0);
  showbullet->setText("Score");

  bgetback= new QPushButton("bgetback", this);
  bgetback->setGeometry(10,190,100,27);
  bgetback->setMinimumSize(0,0);
  bgetback->setText("Get back");

  b61= new QPushButton("g61", this);
  b61->setGeometry(10,10,40,27);
  b61->setMinimumSize(0,0);
  b61->setText("61");
  b61->setIcon(QIcon(QString(":/pics/s61")));

  b62= new QPushButton("g62", this);
  b62->setGeometry(50,10,40,27);
  b62->setMinimumSize(0,0);
  b62->setText("62");
  b62->setIcon(QIcon(QString(":/pics/s62")));

  b63= new QPushButton("g63", this);
  b63->setGeometry(90,10,40,27);
  b63->setMinimumSize(0,0);
  b63->setText("63");
  b63->setIcon(QIcon(QString(":/pics/s63")));

  b64= new QPushButton("g64", this);
  b64->setGeometry(130,10,40,27);
  b64->setMinimumSize(0,0);
  b64->setText("64");
  b64->setIcon(QIcon(QString(":/pics/s64")));

  b71= new QPushButton("g71", this);
  b71->setGeometry(10,40,40,27);
  b71->setMinimumSize(0,0);
  b71->setText("71");
  b71->setIcon(QIcon(QString(":/pics/s71")));


  b81= new QPushButton("g81", this);
  b81->setGeometry(10,70,40,27);
  b81->setMinimumSize(0,0);
  b81->setText("81");
  b81->setIcon(QIcon(QString(":/pics/s81")));

  b91= new QPushButton("g91", this);
  b91->setGeometry(10,100,40,27);
  b91->setMinimumSize(0,0);
  b91->setText("91");
  b91->setIcon(QIcon(QString(":/pics/s91")));

  b101= new QPushButton("g101", this);
  b101->setGeometry(10,130,40,27);
  b101->setMinimumSize(0,0);
  b101->setText("101");
  b101->setIcon(QIcon(QString(":/pics/s101")));

  b72= new QPushButton("g72", this);
  b72->setGeometry(50,40,40,27);
  b72->setMinimumSize(0,0);
  b72->setText("72");
  b72->setIcon(QIcon(QString(":/pics/s72")));

  b82= new QPushButton("g82", this);
  b82->setGeometry(50,70,40,27);
  b82->setMinimumSize(0,0);
  b82->setText("82");
  b82->setIcon(QIcon(QString(":/pics/s82")));

  b92= new QPushButton("g92", this);
  b92->setGeometry(50,100,40,27);
  b92->setMinimumSize(0,0);
  b92->setText("92");
  b92->setIcon(QIcon(QString(":/pics/s92")));

  b102= new QPushButton("g102", this);
  b102->setGeometry(50,130,40,27);
  b102->setMinimumSize(0,0);
  b102->setText("102");
  b102->setIcon(QIcon(QString(":/pics/s102")));

  b73= new QPushButton("g73", this);
  b73->setGeometry(90,40,40,27);
  b73->setMinimumSize(0,0);
  b73->setText("73");
  b73->setIcon(QIcon(QString(":/pics/s73")));

  b83= new QPushButton("g83", this);
  b83->setGeometry(90,70,40,27);
  b83->setMinimumSize(0,0);
  b83->setText("83");
  b83->setIcon(QIcon(QString(":/pics/s83")));

  b93= new QPushButton("g93", this);
  b93->setGeometry(90,100,40,27);
  b93->setMinimumSize(0,0);
  b93->setText("93");
  b93->setIcon(QIcon(QString(":/pics/s93")));

  b103= new QPushButton("g103", this);
  b103->setGeometry(90,130,40,27);
  b103->setMinimumSize(0,0);
  b103->setText("103");
  b103->setIcon(QIcon(QString(":/pics/s103")));

  b74= new QPushButton("g74", this);
  b74->setGeometry(130,40,40,27);
  b74->setMinimumSize(0,0);
  b74->setText("74");
  b74->setIcon(QIcon(QString(":/pics/s74")));

  b84= new QPushButton("g84", this);
  b84->setGeometry(130,70,40,27);
  b84->setMinimumSize(0,0);
  b84->setText("84");
  b84->setIcon(QIcon(QString(":/pics/s84")));

  b94= new QPushButton("g94", this);
  b94->setGeometry(130,100,40,27);
  b94->setMinimumSize(0,0);
  b94->setText("94");
  b94->setIcon(QIcon(QString(":/pics/s94")));

  b104= new QPushButton("g104", this);
  b104->setGeometry(130,130,40,27);
  b104->setMinimumSize(0,0);
  b104->setText("104");
  b104->setIcon(QIcon(QString(":/pics/s104")));

  bpass= new QPushButton("pass", this);
  bpass->setGeometry(10,160,70,30);
  bpass->setMinimumSize(0,0);
  bpass->setText("Pass");

  bvist= new QPushButton("vist", this);
  bvist->setGeometry(80,160,60,30);
  bvist->setMinimumSize(0,0);
  bvist->setText("Whist");

  b86= new QPushButton("g86", this);
  b86->setGeometry(140,160,70,30);
  b86->setMinimumSize(0,0);
  b86->setText("Miser");

  b65= new QPushButton("g65", this);
  b65->setGeometry(170,10,40,27);
  b65->setMinimumSize(0,0);
  b65->setText("65");
  b65->setIcon(QIcon(QString(":/pics/s65")));

  b75= new QPushButton("g75", this);
  b75->setGeometry(170,40,40,27);
  b75->setMinimumSize(0,0);
  b75->setText("75");
  b75->setIcon(QIcon(QString(":/pics/s75")));

  b85= new QPushButton("g85", this);
  b85->setGeometry(170,70,40,27);
  b85->setMinimumSize(0,0);
  b85->setText("85");
  b85->setIcon(QIcon(QString(":/pics/s85")));

  b95= new QPushButton("g95", this);
  b95->setGeometry(170,100,40,27);
  b95->setMinimumSize(0,0);
  b95->setText("95");
  b95->setIcon(QIcon(QString(":/pics/s95")));

  b105= new QPushButton("g105", this);
  b105->setGeometry(170,130,40,27);
  b105->setMinimumSize(0,0);
  b105->setText("105");
  b105->setIcon(QIcon(QString(":/pics/s105")));

  connect( b61, SIGNAL(clicked()),this, SLOT(slotPushButtonClick61( )) );
  connect( b62, SIGNAL(clicked()),this, SLOT(slotPushButtonClick62( )) );
  connect( b63, SIGNAL(clicked()),this, SLOT(slotPushButtonClick63( )) );
  connect( b64, SIGNAL(clicked()),this, SLOT(slotPushButtonClick64( )) );
  connect( b65, SIGNAL(clicked()),this, SLOT(slotPushButtonClick65( )) );

  connect( b71, SIGNAL(clicked()),this, SLOT(slotPushButtonClick71( )) );
  connect( b72, SIGNAL(clicked()),this, SLOT(slotPushButtonClick72( )) );
  connect( b73, SIGNAL(clicked()),this, SLOT(slotPushButtonClick73( )) );
  connect( b74, SIGNAL(clicked()),this, SLOT(slotPushButtonClick74( )) );
  connect( b75, SIGNAL(clicked()),this, SLOT(slotPushButtonClick75( )) );

  connect( b81, SIGNAL(clicked()),this, SLOT(slotPushButtonClick81( )) );
  connect( b82, SIGNAL(clicked()),this, SLOT(slotPushButtonClick82( )) );
  connect( b83, SIGNAL(clicked()),this, SLOT(slotPushButtonClick83( )) );
  connect( b84, SIGNAL(clicked()),this, SLOT(slotPushButtonClick84( )) );
  connect( b85, SIGNAL(clicked()),this, SLOT(slotPushButtonClick85( )) );
  connect( b86, SIGNAL(clicked()),this, SLOT(slotPushButtonClick86( )) );

  connect( b91, SIGNAL(clicked()),this, SLOT(slotPushButtonClick91( )) );
  connect( b92, SIGNAL(clicked()),this, SLOT(slotPushButtonClick92( )) );
  connect( b93, SIGNAL(clicked()),this, SLOT(slotPushButtonClick93( )) );
  connect( b94, SIGNAL(clicked()),this, SLOT(slotPushButtonClick94( )) );
  connect( b95, SIGNAL(clicked()),this, SLOT(slotPushButtonClick95( )) );

  connect( b101, SIGNAL(clicked()),this, SLOT(slotPushButtonClick101( )) );
  connect( b102, SIGNAL(clicked()),this, SLOT(slotPushButtonClick102( )) );
  connect( b103, SIGNAL(clicked()),this, SLOT(slotPushButtonClick103( )) );
  connect( b104, SIGNAL(clicked()),this, SLOT(slotPushButtonClick104( )) );
  connect( b105, SIGNAL(clicked()),this, SLOT(slotPushButtonClick105( )) );

  connect( bpass, SIGNAL(clicked()),this, SLOT(slotPushButtonClickPass( )) );
  connect( bvist, SIGNAL(clicked()),this, SLOT(slotPushButtonClickVist( )) );
  connect( bgetback, SIGNAL(clicked()),this, SLOT(slotGetBackSnos( )) );
  connect( showbullet, SIGNAL(clicked()),this, SLOT(slotShowBullet( )) );
}
